spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "Gateway Server"
    description: "This microservice serves as the API gateway for routing requests to various microservices in the system."
    version: "1.0.0"

logging:
  level:
    com:
      mani:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000
      permitted-number-of-calls-in-half-open-state: 2